### ISSUE TITLE
Nested interface, referenced by union through index-type interface

### ISSUE THREAD

**Issue by Jpunt** [samen-io/samen#28]
Not sure if:

- The title of this issue is semantically correct 😅 
- This is still an issue in next-gen

But anyway, so that we don't forget, this doesn't work properly in 0.8:

```ts
export interface X {
  type: 'x'
}

export interface Y {
  type: 'y'
}

export type Z = X | Y

export interface A {
  b: B
}

export interface B {
  [key: string]: Z
}

export async function example(a: A): Promise<void> {}
```

This leads to `A` and `B` being in the manifest, but `X`, `Y` and `Z` missing. This causes the following error in the CLI:

```
debug.example.ts:12:18 - error TS2304: Cannot find name 'Z'.

12   [key: string]: Z
                    ~
debug.example.ts:12:18 - error TS4049: Return type of index signature from exported interface has or is using private name 'Z'.

12   [key: string]: Z
                    ~
```

This can be fixed by replacing `B` by the following interface:

```ts
export interface B {
  z: Z
}
```

Which is (of course) not what we want to have here, but it causes `X`, `Y` and `Z` to be added to the manifest as expected.

**Comment by kamilafsar** [comment]
Fixed in https://github.com/samen-io/samen/releases/tag/v0.9.3
