### ISSUE TITLE
Telefunc Collab

### ISSUE THREAD

**Issue by brillout** [samen-io/samen#58]
Author of [Telefunc](https://telefunc.com/) here.

Nice work on Samen, congrats 👌.

If you guys are up for some kind of collaboration, let me know!

**Comment by Jpunt** [comment]
Thanks man, you too! Let's schedule a meet soon to discuss this. Will get back to you asap 👍

**Comment by Jpunt** [comment]
@brillout I've sent you an email about this 😊

**Comment by brillout** [comment]
Yes I've seen :-).

I think the biggest blocker for this is whether we want to focus on Samen or Telefunc.

I'm obviously biased, but so far I believe Telefunc to be the "superior" approach. I don't mean any offense, and I'm more than happy to be shown wrong!

I know it's very tough but I think it's very well worth it if we somehow manage to align ourselves. It'd tremendously amplify our collective impact.

How do you see this?

**Comment by Jpunt** [comment]
We feel the same, but the other way around 😄 What do you think about having a call, where you can do a demo of telefunc and tell us what's better about it, and we do the same to you?

**Comment by Jpunt** [comment]
Closing this issue for now, feel free to contact us at hi@samen.io!
